### ISSUE TITLE
Global 120Hz not working

### ISSUE THREAD

**Issue by russel5** [Oosl/ColorOSTool#22]
Phone - Oneplus 9 pro
Firmware - ColorOS 12.1 (C.62)
ColorOsTool - 1.9.9.9

Logs from lsposed
`[ 2022-04-24T20:56:05.873     1000:  4553:  4553 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.oplus.settings.feature.display.ScreenRefreshRateFragment#e(int)#exact
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.h(Unknown Source:0)
	at de.robv.android.xposed.c.get(Unknown Source:15)
	at java.util.Optional.orElseThrow(Optional.java:286)
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:21)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:4)
	at colorostool.e8.afterHookedMethod(:2)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:151)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1193)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1396)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6997)
	at android.app.ActivityThread.access$1800(ActivityThread.java:253)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)`

If you are need addiditional logs -- https://drive.google.com/file/d/1jYrHpSZC6Wc3SeWUgIpzH9zF2oQAOH-P/view?usp=sharing

**Comment by Oosl** [comment]
Thanks for your report, it`s known issue and may not be fixed. I recommend to use[ dfps](https://github.com/yc9559/dfps) to get a better refresh rate experience.
