### ISSUE TITLE
[bug] 移除安装前，因版本相同、低版本等弹出的警告提示 失效(12）

### ISSUE THREAD

**Issue by NextAlone** [Oosl/ColorOSTool#4]
移除安装前，因版本相同、低版本等弹出的警告提示 失效(Color OS 12）

**Comment by Oosl** [comment]
我这里没有失效，建议确认功能开启，如果还是失效，请附上lsp日志

**Comment by NextAlone** [comment]
https://pastebin.com/uEY6L6nF

continue oppo safe install 方法已移除

**Comment by NextAlone** [comment]
![Screenshot_2021-09-30-23-42-54-49_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://user-images.githubusercontent.com/12210746/135487628-0e9923ac-b9e2-4ae9-930a-9f34dfad2dd1.jpg)

**Comment by Oosl** [comment]
这就奇了怪了，能把你的机型，系统版本信息，以及提取一份Package installer的安装包给我么？![Screenshot.jpg](https://user-images.githubusercontent.com/27420243/135533928-c8d6fc23-c27a-4a28-b468-33cefddffded.jpg)

**Comment by NextAlone** [comment]
> https://pastebin.com/uEY6L6nF
> 
> continue oppo safe install 方法已移除，导致异常

    https://h13.baidupan.com/100113bb/2021/10/01/f8cf0a379c217c321f2af39ed1127aab.apk?st=mnoU2zCRRPAvOUiOwYznmw&e=1633068034&b=BLMPtVDEUrBZmF_bhALVV3VODDLUFqgeIA7gArlLQB_bIF_a1vQAudR7gXfX1YCYQUvAmEIegAzBTcCYl1mUnsCYQQmD2Q_c&fi=53344187&pid=123-124-147-53&up=2

OP9Pro c18

**Comment by Oosl** [comment]
> > https://pastebin.com/uEY6L6nF
> > continue oppo safe install 方法已移除，导致异常
> 
> ```
> https://h13.baidupan.com/100113bb/2021/10/01/f8cf0a379c217c321f2af39ed1127aab.apk?st=mnoU2zCRRPAvOUiOwYznmw&e=1633068034&b=BLMPtVDEUrBZmF_bhALVV3VODDLUFqgeIA7gArlLQB_bIF_a1vQAudR7gXfX1YCYQUvAmEIegAzBTcCYl1mUnsCYQQmD2Q_c&fi=53344187&pid=123-124-147-53&up=2
> ```
> 
> OP9Pro c18  

试试  
[ColorOSTool_v1.7.zip](https://github.com/Oosl/ColorOSTool/files/7264571/ColorOSTool_v1.7.zip)

**Comment by NextAlone** [comment]
> > > https://pastebin.com/uEY6L6nF
> > > continue oppo safe install 方法已移除，导致异常
> > 
> > ```
> > https://h13.baidupan.com/100113bb/2021/10/01/f8cf0a379c217c321f2af39ed1127aab.apk?st=mnoU2zCRRPAvOUiOwYznmw&e=1633068034&b=BLMPtVDEUrBZmF_bhALVV3VODDLUFqgeIA7gArlLQB_bIF_a1vQAudR7gXfX1YCYQUvAmEIegAzBTcCYl1mUnsCYQQmD2Q_c&fi=53344187&pid=123-124-147-53&up=2
> > ```
> > 
> > OP9Pro c18  
> 
> 试试  
> [ColorOSTool_v1.7.zip](https://github.com/Oosl/ColorOSTool/files/7264571/ColorOSTool_v1.7.zip)
> 
> 
> 

还是不行，
```
[ 2021-10-03T20:26:56.868    10169: 24457: 24457 I/LSPosed         ] Loading modules for com.android.packageinstaller/10169
[ 2021-10-03T20:26:56.869    10169: 24457: 24457 I/LSPosed-Bridge  ] Loading module com.oosl.colorostool from /data/app/~~4UG5GweEj-kyjJkEw3Lk2Q==/com.oosl.colorostool-FBim1gpUg86svNIzNSGuoA==/base.apk
[ 2021-10-03T20:26:56.885    10169: 24457: 24457 I/LSPosed-Bridge  ]   Loading class com.oosl.colorostool.XposedInit
[ 2021-10-03T20:26:56.924    10169: 24457: 24457 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.packageinstaller.oplus.common.AccountVerifyControl#needAccountVerify(android.content.Context,java.lang.String)#exact
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:79)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at com.oosl.colorostool.plugin.HookPackageInstaller.removeVerify(HookPackageInstaller.java:47)
	at com.oosl.colorostool.plugin.HookPackageInstaller.hook(HookPackageInstaller.java:25)
	at com.oosl.colorostool.XposedInit.handleLoadPackage(XposedInit.java:24)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at A1.afterHookedMethod(Unknown Source:111)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1327)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3041)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3033)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6909)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1700(ActivityThread.java:253)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8175)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

**Comment by NextAlone** [comment]
有一个更新 

https://ducts.lanzoui.com/iKPalutz69e

**Comment by Oosl** [comment]
emmmm，竟然又更新了。算了算了，等公测版吧，你这内测看起来更新太勤快了，等代码稳定再说🥲

**Comment by NextAlone** [comment]
> emmmm，竟然又更新了。算了算了，等公测版吧，你这内测看起来更新太勤快了，等代码稳定再说🥲

公测了公测了，搞起来

**Comment by Oosl** [comment]
> 公测了公测了，搞起来

差不多搞完了，等再把兼容cos11的代码丢掉就更新🌚

**Comment by Oosl** [comment]
675f8e1365cd197c1b033253e00d62d65ca0e319  已适配，下载[最新版](https://github.com/Xposed-Modules-Repo/com.oosl.colorostool/releases/latest)试试

**Comment by NextAlone** [comment]
> 675f8e1365cd197c1b033253e00d62d65ca0e319  已适配，下载[最新版](https://github.com/Xposed-Modules-Repo/com.oosl.colorostool/releases/latest)试试

可以了
